#!/bin/bash

### WRAPPER BASH SCRIPT TO DOWNLOAD AND RUN RUST BINARY ###

set -e

# setup defaults for all environment variables
export AUTOSAVER_HOME="${AUTOSAVER_HOME:-$HOME}"
export AUTOSAVER_ROOT="${AUTOSAVER_ROOT:-$(dirname "$(realpath "${BASH_SOURCE[0]}")")}"

# local paths
LOCAL_BIN_PATH_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/autosaver"
LOCAL_BIN_PATH="$LOCAL_BIN_PATH_DIR/autosaver"
# remote url
REMOTE_RELEASE_URL="https://github.com/daniele47/autosaver/releases/latest/download"
REMOTE_BIN_NAME=""
REMOTE_RELEASE_URL_BIN=""
# platform
PLATFORM="$(uname -s)"
ARCHITECTURE="$(uname -m)"

function download_url() {
    local url="$1"
    local output="$2"
    if command -v curl &>/dev/null; then
        curl -L --fail --show-error --progress-bar --output "$output" "$url"
    elif command -v wget &>/dev/null; then
        wget --no-verbose --show-progress --output-document="$output" "$url"
    else
        echo "ERROR: Neither curl nor wget found. Please install one." >&2
        return 1
    fi
}

# update/uninstall
if [[ ! -f "$LOCAL_BIN_PATH" && ! -v UNINSTALL || -v INSTALL ]]; then
    # get platform / os dependent variables populated
    case "$PLATFORM" in
    Linux)
        case "$ARCHITECTURE" in
        armv7l) REMOTE_BIN_NAME="autosaver-armv7-unknown-linux-musleabihf.tar.gz" ;;
        aarch64) REMOTE_BIN_NAME="autosaver-aarch64-unknown-linux-musl.tar.gz" ;;
        x86_64) REMOTE_BIN_NAME="autosaver-x86_64-unknown-linux-musl.tar.gz" ;;
        *) echo "$PLATFORM with $ARCHITECTURE is not supported" && exit 1 ;;
        esac
        ;;
    *) echo "$PLATFORM is not supported" && exit 1 ;;
    esac

    # delete whatever was already in the cache directory
    rm -rf "$LOCAL_BIN_PATH_DIR"
    mkdir -p "$LOCAL_BIN_PATH_DIR"

    echo "(1/3) Downloading latest archive release..."
    REMOTE_RELEASE_URL_BIN="$REMOTE_RELEASE_URL/$REMOTE_BIN_NAME"
    download_url "$REMOTE_RELEASE_URL_BIN" "$LOCAL_BIN_PATH_DIR/archive.tar.gz"

    echo "(2/3) Decompossing downloaded archive..."
    tar -xzf "$LOCAL_BIN_PATH_DIR/archive.tar.gz" -C "$LOCAL_BIN_PATH_DIR"

    echo "(3/3) Cleanup temporary files..."
    rm "$LOCAL_BIN_PATH_DIR/archive.tar.gz"

    echo -n "Autosaver installed/updated: "
    "$LOCAL_BIN_PATH" --version

    echo -e "--------------------------------------------------------------------------------\n"
elif [[ -v UNINSTALL ]]; then
    if [[ ! -d "$LOCAL_BIN_PATH_DIR" ]]; then
        echo "Autosaver was already uninstalled!"
    else
        echo "(1/1) Uninstalling autosaver by deleting the cache directory..."
        rm -rf "$LOCAL_BIN_PATH_DIR"
        echo "Autosaver was succesffully uninstalled!"
    fi
    exit 0
fi

# run binary
"$LOCAL_BIN_PATH" "$@"
