#!/bin/bash

### WRAPPER BASH SCRIPT TO DOWNLOAD AND RUN RUST BINARY ###

set -e

# setup defaults for all environment variables
export AUTOSAVER_HOME="${AUTOSAVER_HOME:-$HOME}"
export AUTOSAVER_ROOT="${AUTOSAVER_ROOT:-$(dirname "$(realpath "${BASH_SOURCE[0]}")")}"

# local paths
LOCAL_BIN_PATH_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/autosaver"
LOCAL_BIN_PATH="$LOCAL_BIN_PATH_DIR/autosaver"
# remote url
REMOTE_RELEASE_URL_LATEST="https://github.com/daniele47/autosaver/releases/latest/download"
REMOTE_RELEASE_URL_VERSION="https://github.com/daniele47/autosaver/releases/download"
REMOTE_RELEASE_URL=""
REMOTE_BIN_NAME=""

# update/uninstall
if [[ ! -f "$LOCAL_BIN_PATH" && ! -v UNINSTALL || -v INSTALL ]]; then
    # previous binary version
    OLD_VERSION="$($LOCAL_BIN_PATH --version 2>/dev/null | tr -d '\n ')"
    [[ -z "$OLD_VERSION" ]] && OLD_VERSION="\e[1;31mmissing\e[m"

    # get platform / os dependent variables populated
    PLATFORM="$(uname -s)"
    ARCHITECTURE="$(uname -m)"
    case "$PLATFORM" in
    Linux)
        case "$ARCHITECTURE" in
        armv7l) REMOTE_BIN_NAME="autosaver-armv7-unknown-linux-musleabihf.tar.gz" ;;
        aarch64) REMOTE_BIN_NAME="autosaver-aarch64-unknown-linux-musl.tar.gz" ;;
        x86_64) REMOTE_BIN_NAME="autosaver-x86_64-unknown-linux-musl.tar.gz" ;;
        *) echo "$PLATFORM with $ARCHITECTURE is not supported" && exit 1 ;;
        esac
        ;;
    *) echo "$PLATFORM is not supported" && exit 1 ;;
    esac

    # delete whatever was already in the cache directory
    mkdir -p "$LOCAL_BIN_PATH_DIR"

    # download operations
    if [[ -n "$INSTALL" ]]; then # use tagged version
        REMOTE_RELEASE_URL="$REMOTE_RELEASE_URL_VERSION/$INSTALL/$REMOTE_BIN_NAME"
    else # use latest version
        REMOTE_RELEASE_URL="$REMOTE_RELEASE_URL_LATEST/$REMOTE_BIN_NAME"
    fi
    echo "(1/3) Downloading latest archive release from '$REMOTE_RELEASE_URL' ..."
    url="$REMOTE_RELEASE_URL"
    output=$LOCAL_BIN_PATH_DIR/archive.tar.gz""
    if command -v curl &>/dev/null; then
        curl -L --fail --show-error --progress-bar --output "$output" "$url"
    elif command -v wget &>/dev/null; then
        wget --no-verbose --show-progress --output-document="$output" "$url"
    else
        echo "ERROR: Neither curl nor wget found. Please install one." >&2
        return 1
    fi

    # decompression operations
    echo "(2/3) Decompossing downloaded archive..."
    tar -xzf "$output" -C "$LOCAL_BIN_PATH_DIR"

    # cleanup operations
    echo "(3/3) Cleanup temporary files..."
    rm "$output"

    echo -n "Autosaver installed/updated: "
    echo -en "$OLD_VERSION ---> " && "$LOCAL_BIN_PATH" --version

    echo -e "--------------------------------------------------------------------------------\n"
elif [[ -v UNINSTALL ]]; then
    # uninstall operations
    if [[ ! -d "$LOCAL_BIN_PATH_DIR" ]]; then
        echo "Autosaver was already uninstalled!"
    else
        echo "(1/1) Uninstalling autosaver by deleting the cache directory..."
        rm -rf "$LOCAL_BIN_PATH_DIR"
        echo "Autosaver was succesffully uninstalled!"
    fi
    exit 0
fi

# run binary
"$LOCAL_BIN_PATH" "$@"
