/! kind module
/! id firefox

/! policy notdiff
.var/app/org.mozilla.firefox/config/mozilla/firefox/profiles.ini
.var/app/org.mozilla.firefox/config/mozilla/firefox/installs.ini
.var/app/org.mozilla.firefox/config/mozilla/firefox/kvgujw0x.customized/prefs.js
.var/app/org.mozilla.firefox/config/mozilla/firefox/kvgujw0x.customized/search.json.mozlz4

/! cleanup .var/app/org.mozilla.firefox
