# simple fixes
set -as terminal-features ',xterm*:RGB'
set -g mouse on
set -g escape-time 0
set -g history-limit 10000

# split preserve current directory
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# fix indexes
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# nicer style
set -g status-style bg=green,fg=black
set -g status-left ""
set -g status-right "[#S]"
set -g pane-border-lines simple

# keymaps
bind h split-window -h
bind v split-window -v
