set -as terminal-features ',xterm*:RGB'
set -g mouse on

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set -g base-index 1
set -g pane-base-index 1

set -g renumber-windows on
