[Audio]
Volume=100

[General]
FloatingFooterTrigger=BottomMouseMovement
ShowHeader=false
ShowPreviewThumbnail=true

[Playback]
RestoreFilePosition=true

[Playlist]
CanToggleWithMouse=false
LoadSiblings=false
OpenWithSingleClick=true
PlaybackBehavior=StopAfterLast
ShowToolbar=false

[Video]
ScreenshotFormat=png
