/! kind module
/! id kde

/! policy notdiff
.config/baloofilerc
.config/bluedevilglobalrc
.config/kdeglobals
.config/kglobalshortcutsrc
.config/kscreenlockerrc
.config/ksmserverrc
.config/kwinrc
.config/kxkbrc
.config/plasma-localerc
.config/plasmanotifyrc
.config/plasma-org.kde.plasma.desktop-appletsrc
.config/plasmaparc
.config/plasmarc
.config/plasmashellrc
.config/systemsettingsrc
