/! kind module
/! id hide-apps

.local/share/applications/org.kde.drkonqi.coredump.gui.desktop
.local/share/applications/org.kde.kdeconnect.app.desktop
.local/share/applications/org.kde.kdeconnect.sms.desktop
.local/share/applications/org.kde.plasma-welcome.desktop
