/! kind module
/! id neovim

.config/nvim

/! policy exclude
.config/nvim/nvim-pack-lock.json

/! cleanup .local/share/nvim
/! cleanup .local/state/nvim
/! cleanup .cache/nvim
/! cleanup .config/nvim
