/! type module
/! id kde

/! policy notdiff

.config/baloofilerc
.config/kdeglobals
.config/kglobalshortcutsrc
.config/kscreenlockerrc
.config/kwinrc
.config/plasma-localerc
.config/plasma-org.kde.plasma.desktop-appletsrc
.config/plasmanotifyrc
.config/plasmaparc
.config/plasmarc
.config/plasmashellrc
.config/systemsettingsrc
.config/ksmserverrc

